### ISSUE TITLE
gps accuracy

### ISSUE THREAD

**Issue by anvartur** [dualav/XGPS-SDK-Android#1]
We bought a few xgps150A devices and want to integrate into our application. I looked through the api of XGPSManager but haven't seen a function to get accuracy of current GPS position. Would you pls comment on this matter? Any suggestions to get accuracy?

**Comment by dualav** [comment]
Dear anvartur,
The DOP means an accuracy, try to use below
        int valueHorizontal = xgpsManager.getHDOP();
        int valueVertical = xgpsManager.getVDOP();
        int value3D = xgpsManager.getPDOP();
