### ISSUE TITLE
Can't get firmware version and battery level from XGPS150A.

### ISSUE THREAD

**Issue by k-tigre** [dualav/XGPS-SDK-Android#2]
I test sample with XGPS150A (firmware 2.1.2 checked in SkyPro GPS Status Tool) and find that SKD don't provide firmware version (always empty) and battery level (always zero value).

**Comment by yuchi79** [comment]
I'll check it.

**Comment by k-tigre** [comment]
@yuchi79 Do you have any update?

**Comment by dualav** [comment]
It has been updated. Sorry too late.
